ALTER TABLE users
	ADD COLUMN reputation		INTEGER NOT NULL,
	ADD COLUMN creationDate 	TIMESTAMP WITHOUT TIME ZONE,
	ADD COLUMN displayName		VARCHAR(30) NOT NULL,
	ADD COLUMN lastAccess		TIMESTAMP WITHOUT TIME ZONE,
	ADD COLUMN location			VARCHAR(120),
	ADD COLUMN aboutText		VARCHAR,
	ADD COLUMN views			INTEGER NOT NULL,
	ADD COLUMN upVotes			INTEGER NOT NULL,
	ADD COLUMN downVotes		INTEGER NOT NULL,
	ADD COLUMN emailHash		VARCHAR,
	ADD COLUMN age				INTEGER;

ALTER TABLE users
	DROP COLUMN IF EXISTS name;
